config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :genres, only: [:show]
  
  resources :artists do
    resources :songs, only: [:new, :index, :show]
  end
  
  resources :songs
  resources :genres
  
  devise_for :users, :controllers => {registrations: 'registrations'}
  root to: 'application#home'
  
  get '/auth/facebook/callback' => 'sessions#createf'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  has_many :genres, through: :songs
  has_many :users, through: :songs
  
  #belongs_to :genre
  
  accepts_nested_attributes_for :songs
  
  validates_presence_of :name
  
  def self.alphabetical_order
    order(:name)
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :songs
  has_many :artists, through: :songs
  
  # accepts_nested_attributes_for :songs
  
  validates :genre_name, presence: true
  
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  #belongs_to :genre
  belongs_to :user
  
  validates :title, presence: true

  accepts_nested_attributes_for :artist

  def artist_name=(name)
    artist = Artist.find_or_create_by(name: name)
    self.artist = artist
  end
  
  def artist_name
    self.try(:artist).try(:name)
  end
  
end

app/models/user.rb
class User < ApplicationRecord  #ActiveRecird__Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :songs
  has_many :artists, through: :songs

  validates :email, uniqueness: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def home
  end
end

app/controllers/artist_controller.rb
class ArtistController < ApplicationController
  def show
    @artist = Artist.find(params[:id])
  end

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
    @artist.songs.build(name: "Title", album: "Album")
  end

  def create
    Artist.create(artist_params)
    redirect_to artist_path
  end

  def artist_params
    params.require(:artist).permit(
      :title,
      songs_attributes: [ :name, :album ]
    )
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
 def index
        @artists = Artist.all
    end

    def new
        @artist = Artist.new
    end

    def create
        @artist = Artist.new(artist_params)
        if @artist.save
            redirect_to artists_path
        else
            render :new
        end
    end

    private

    def artist_params
        params.require(:artist).permit(:name, :type, :writer, :song_id, song_attributes: [:title])
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
        def sign_up_params
            params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
        end
        
        def account_update_params
            params.require(:user).permit(:username, :name, :email, :password, :password_confirmation)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

  def createf
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
    end
 
    session[:user_id] = @user.id
 
    render '/devise/sessions/new'
  end
 
  private
 
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
        if @artist = Artist.find_by_id(params[:artist_id])
            @songs = @artist.songs.all
        else
            @songs = Song.all
        end   

    end

    def new
        if @artist = Artist.find_by_id(params[:artist_id])
            @song = @artist.songs.build
        else
            @song = Song.new
        end    
    end

    def create
        @song = current_user.songs.build(song_params)
        if @song.save
            redirect_to song_path(@song)
        else
            render :new
        end
    end

    def show
        @song = Song.find_by_id(params[:id])
    end

    private
    
    def song_params
        params.require(:song).permit(:title, :album_name, :artist, :release_year, :genre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def display_artist(song)
    song.artist.nil? ? link_to("Add Artist", edit_song_path(song)) : link_to(song.artist_name, artist_path(song.artist))
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/application/home.html.erb
<!DOCTYPE html>
<html>
<head>
  
</head>

<body>
  
  <h1>Welcome To Your User Music Library!</h1>
  <h4>Please Sign up or Log in to access your User Library</h4>

</body>

</html>

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= f.label "Artist Name:" %>
  <%= f.text_field :name %><br/>

  <%= f.fields_for :songs do |sec_form| %>
    <%= sec_form.label :title %>
    <%= sec_form.text_field :title %><br/>

    <%= sec_form.label :album_name %>
    <%= sec_form.text_field :album_name %><br/>
  <% end %>

  <%= f.submit %>
<% end %>


<% if @artist.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@artist.errors.count, "An error") %>
      prohibited this artist's information from being saved:
    </h2>
 
    <ul>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/artists/index.html.erb
<h1>Artists In Library:</h1>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_songs_path(artist) %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<%= render 'form' %>

app/views/artists/show.html.erb
<h2> <%= @artist.name %></h2>

<h3>LIST OF SONGS IN LIBRARY</h3>

<ul>
  <% @artist.songs.each do |song| %>
    <li><%= link_to song.title, artist_song_path(@artist, song) %></li>
  <% end %>
</ul>

app/views/genres/show.html.erb
<%= @genre %>
<%= link_to @genre.artist, artist_path(@genre.artist_id) %>
<%= link_to @genre.song, song_path(@genre.song_id) %>

app/views/layouts/_nav.html.erb
<ul>
    <li><%= link_to "Home", root_path %></li>
    <% if !user_signed_in? %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
        
          <% if session[:user_id] %>
              <h1><%= @user.name %></h1>
              <h2>Email: <%= @user.email %></h2>
              <h2>Facebook UID: <%= @user.uid %></h2>
              <img src="<%= @user.image %>">
          <% else %>
            <%= link_to('Log in with Facebook!', '/auth/facebook') %>
          <% end %>
          
    <% else %>
        <li><%= link_to "Add a New Artist to Library", new_artist_path %> </li>
        <li><%= link_to "Add a New Song to Library", new_song_path %> </li>
        <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <% end %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>USER LIBRARY</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br/>
  <%= f.label :album_name %>
  <%= f.text_field :album_name %><br/>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %><br/>
  <%= f.label :release_year %>
  <%= f.text_field :release_year %><br/>

  <%= f.fields_for :genres do |sec_form| %>
    <%= sec_form.label :genre %>
    <%= sec_form.text_field :genre_name %><br/>
  <% end %>

  <%= f.submit %>
<% end %>


<% if @song.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@song.errors.count, "Error") %>
      prohibited this song from being saved:
    </h2>
 
    <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing <%= @song.title %> by <%= @song.artist_name %></h1>

<%= render 'form' %>

<%= link_to 'Cancel Editing', @song %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<div><%= link_to 'Create Song', new_song_path %></div>
<br />

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist Name</th>
      <th>Year</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.artist_name %></td>
        <td><%= song.release_year %></td>
        <td>
          <%= link_to ' View', song %> |
          <%= link_to ' Edit', edit_song_path(song) %> |
          <%= link_to ' Delete', song, method: :delete, data: { confirm: 'For real?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/new.html.erb
<h1>Create a Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= link_to @song.title, song_path(@song) %></h1>
<h3> by <%= display_artist(@song) %></h3>
  
  <p>
    Released in:
    <strong><%= @song.release_year %></strong>
    On The Album:
    <strong><%= @song.album_name %></strong>
    <strong>Genre:</strong>
      <%= @song.genre_name %>
  </p>

<%= link_to 'Edit', edit_song_path(@song) %>

<%= link_to "All Songs", songs_path %>

<form method="post" action="/songs/<%=@song.id%>">
  <input type="hidden" name="_method" value="DELETE" />
  <input type="submit" value="DELETE" />
</form>